[package]
name = "opencam-desktop"
version = "0.1.0"
edition = "2021"

[lib]
name = "opencam_lib"
crate-type = ["staticlib", "cdylib", "rlib"]

[[bin]]
name = "opencam-desktop"
path = "src/main.rs"

[build-dependencies]
tauri-build = { version = "1.5", features = [] }

[dependencies]
tauri              = { version = "1.6",  features = ["shell-open"] }
serde              = { version = "1",    features = ["derive"] }
serde_json         = "1"
tokio              = { version = "1",    features = ["full"] }
tokio-tungstenite  = "0.21"
futures-util       = "0.3"
local-ip-address   = "0.6"
log                = "0.4"
env_logger         = "0.11"

[features]
custom-protocol = ["tauri/custom-protocol"]

[profile.release]
panic = "abort"
codegen-units = 1
